# This is a basic workflow to help you get started with Actions

name: Create and publish the bundle

# Controls when the workflow will run
on: workflow_dispatch
  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Create bundle
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          tar -czf codeql-bundle.tar.gz codeql          
          gh release create codeql-bundle-20220214-$(git rev-parse --short $GITHUB_SHA) codeql-bundle.tar.gz
